#!/usr/bin/python3

import sys

from mako.template import Template

t = Template(filename=sys.argv[1])
r = t.render(param=int(sys.argv[2]))

fn = sys.argv[1].split('/')[-1].split('.')[0] + str(sys.argv[2]) + ".tsl"
f = open("specs/tsl-files/" + fn, 'w')
f.write(r)
f.close()
